name: "CI Unit Tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nginx:
          - 1.23.0
          - 1.22.0
          - 1.21.5
          - 1.20.2
          - 1.18.0
          - 1.16.1
          - 1.14.2
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        persist-credentials: false
    - name: Install Test::Nginx
      run: sudo cpan -Ti Test::Nginx Test::Nginx::Socket
    - name: Build
      run: /bin/bash .scripts/ci-build.sh "${{ matrix.nginx }}"
    - name: Unit Tests
      run: /bin/bash .scripts/ci-test.sh